name: $(SemVer)

trigger:
  batch: true
  branches:
    include:
      - master
      - release/*
      - develop
      - feature/*
  paths:
    include:
      - src/*
      - Directory.Build.props
      - Directory.Build.targets

pr:
  autoCancel: true
  branches:
    include:
      - release/*
  paths:
    include:
      - src/*
      - Directory.Build.props
      - Directory.Build.targets

variables:
  - template: ../.config/variables.yml
  - group: global

pool:
  vmImage: $(BuildImage)

stages:
  - stage: NuGet
    displayName: NuGet
    dependsOn: []
    jobs:
      - template: ../.templates/nuget-ado.yml
        parameters:
          buildConfig: "Release"
      - template: ../.templates/nuget.yml
        parameters:
          buildConfig: "Release"
        condition: contains('$(branchType)', 'release')
